// All 100 calculators - new additions to existing 15
export type NewCalculator = {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  category: "gst" | "tax" | "payroll" | "finance" | "investment" | "loan" | "business" | "banking";
  formula: string;
  h1: string;
  intro: string;
  howItWorks: string;
  fields: { label: string; type: "number" | "select" | "text"; placeholder?: string; options?: string[] }[];
  examples: { label: string; inputs: Record<string, number | string>; result: string }[];
  faqs: { question: string; answer: string }[];
  blogSlugs: string[];
};

export const NEW_CALCULATORS: NewCalculator[] = [
  // ── FINANCE / LOAN ────────────────────────────────────────────────────────
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    shortName: "EMI",
    description: "Calculate monthly EMI for home, car, and personal loans",
    icon: "emi",
    category: "loan",
    formula: "EMI = P × r × (1+r)^n / [(1+r)^n − 1]",
    h1: "EMI Calculator India 2025 — Home, Car & Personal Loan",
    intro: "Calculate your Equated Monthly Instalment (EMI) instantly for any loan. Get a full amortisation breakdown showing principal vs interest for every month.",
    howItWorks: "Enter loan amount, annual interest rate, and tenure in months. The calculator applies the reducing balance formula and shows your exact monthly EMI, total interest, and total payment.",
    fields: [
      { label: "Loan Amount (₹)", type: "number", placeholder: "e.g. 5000000" },
      { label: "Annual Interest Rate (%)", type: "number", placeholder: "e.g. 8.5" },
      { label: "Tenure (Months)", type: "number", placeholder: "e.g. 240" },
    ],
    examples: [
      { label: "₹50L Home Loan at 8.5% for 20 years", inputs: { amount: 5000000, rate: 8.5, months: 240 }, result: "EMI: ₹43,391 | Total Interest: ₹54.1L | Total Payment: ₹1.04Cr" },
      { label: "₹10L Car Loan at 9% for 5 years", inputs: { amount: 1000000, rate: 9, months: 60 }, result: "EMI: ₹20,758 | Total Interest: ₹2.45L | Total Payment: ₹12.45L" },
      { label: "₹5L Personal Loan at 14% for 3 years", inputs: { amount: 500000, rate: 14, months: 36 }, result: "EMI: ₹17,089 | Total Interest: ₹1.15L | Total Payment: ₹6.15L" },
    ],
    faqs: [
      { question: "What is EMI?", answer: "EMI (Equated Monthly Instalment) is the fixed monthly amount paid to repay a loan. It includes both principal and interest components calculated using the reducing balance method." },
      { question: "What is the EMI formula?", answer: "EMI = P × r × (1+r)^n / [(1+r)^n − 1]. Where P = Principal, r = monthly interest rate (annual rate/12/100), n = tenure in months." },
      { question: "How can I reduce my EMI?", answer: "Four ways: 1) Increase tenure (lower EMI but more interest), 2) Make a larger down payment, 3) Get a lower interest rate (balance transfer), 4) Prepay the principal to reduce outstanding balance." },
      { question: "Does prepayment reduce EMI or tenure?", answer: "Most banks let you choose. Reducing tenure saves more interest. Reducing EMI improves monthly cash flow. For home loans, reducing tenure is generally the better financial decision." },
      { question: "What is the maximum EMI I should pay?", answer: "RBI's FOIR (Fixed Obligation to Income Ratio) guideline: total EMIs should not exceed 40-50% of your net monthly income. Most banks follow this when approving loans." },
    ],
    blogSlugs: ["what-is-emi", "emi-formula-explained", "how-to-reduce-emi", "home-loan-emi-guide", "emi-vs-prepayment"],
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    shortName: "SIP",
    description: "Calculate SIP returns and mutual fund wealth growth",
    icon: "sip",
    category: "investment",
    formula: "FV = P × [(1+r)^n − 1] / r × (1+r)",
    h1: "SIP Calculator India 2025 — Mutual Fund Return Calculator",
    intro: "Calculate how much your Systematic Investment Plan (SIP) will grow over time. See the power of compounding with monthly SIP projections for any tenure and return rate.",
    howItWorks: "Enter monthly SIP amount, expected annual return rate, and investment period. The calculator uses the future value of annuity formula to project your wealth corpus.",
    fields: [
      { label: "Monthly SIP Amount (₹)", type: "number", placeholder: "e.g. 5000" },
      { label: "Expected Annual Return (%)", type: "number", placeholder: "e.g. 12" },
      { label: "Investment Period (Years)", type: "number", placeholder: "e.g. 20" },
    ],
    examples: [
      { label: "₹5,000/month for 20 years at 12%", inputs: { monthly: 5000, rate: 12, years: 20 }, result: "Invested: ₹12L | Corpus: ₹49.96L | Wealth Gain: ₹37.96L" },
      { label: "₹10,000/month for 15 years at 12%", inputs: { monthly: 10000, rate: 12, years: 15 }, result: "Invested: ₹18L | Corpus: ₹50.46L | Wealth Gain: ₹32.46L" },
      { label: "₹1,000/month for 30 years at 12%", inputs: { monthly: 1000, rate: 12, years: 30 }, result: "Invested: ₹3.6L | Corpus: ₹35.29L | Wealth Gain: ₹31.69L" },
    ],
    faqs: [
      { question: "What is SIP?", answer: "SIP (Systematic Investment Plan) is a method of investing a fixed amount regularly (usually monthly) in mutual funds. It leverages rupee-cost averaging and the power of compounding." },
      { question: "What return should I assume for SIP calculator?", answer: "For equity mutual funds: use 10-12% for conservative estimates. Nifty 50 has delivered ~12-13% CAGR over 20 years. For debt funds use 6-8%. Hybrid funds: 9-10%." },
      { question: "Can I increase SIP amount over time?", answer: "Yes, this is called Step-Up SIP. Increasing SIP by 10% annually dramatically boosts your corpus. ₹5,000/month with 10% annual step-up for 20 years at 12% grows to ~₹1.2Cr vs flat ₹50L." },
      { question: "Is SIP safe?", answer: "Equity SIPs carry market risk and NAV fluctuates daily. However, no 15+ year rolling period in Nifty 50 history has given negative returns. For capital protection, choose debt fund SIPs." },
      { question: "How is SIP different from lump sum?", answer: "SIP invests fixed amounts periodically — buying more units when markets fall (rupee-cost averaging). Lump sum invests all at once — better if markets are at a low, worse if at peak. SIP reduces timing risk." },
    ],
    blogSlugs: ["what-is-sip", "sip-calculator-guide", "sip-vs-lump-sum", "best-sip-mutual-funds", "sip-step-up-strategy"],
  },
  {
    slug: "fd-calculator",
    name: "FD Calculator",
    shortName: "FD",
    description: "Calculate Fixed Deposit maturity amount and interest earned",
    icon: "fd",
    category: "banking",
    formula: "A = P × (1 + r/n)^(n×t)",
    h1: "FD Calculator India 2025 — Fixed Deposit Maturity Calculator",
    intro: "Calculate your Fixed Deposit maturity amount and interest earned for any bank, rate, and tenure. Supports quarterly, monthly, and annual compounding.",
    howItWorks: "Enter principal amount, annual interest rate, tenure, and compounding frequency. The calculator applies compound interest formula to show exact maturity value and interest earned.",
    fields: [
      { label: "Principal Amount (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Annual Interest Rate (%)", type: "number", placeholder: "e.g. 7.5" },
      { label: "Tenure (Months)", type: "number", placeholder: "e.g. 12" },
      { label: "Compounding", type: "select", options: ["Quarterly", "Monthly", "Annually", "Simple Interest"] },
    ],
    examples: [
      { label: "₹1L at 7.5% for 1 year (quarterly)", inputs: { principal: 100000, rate: 7.5, months: 12 }, result: "Maturity: ₹1,07,714 | Interest: ₹7,714" },
      { label: "₹5L at 8% for 3 years (quarterly)", inputs: { principal: 500000, rate: 8, months: 36 }, result: "Maturity: ₹6,34,125 | Interest: ₹1,34,125" },
      { label: "₹10L at 9% for 5 years (quarterly)", inputs: { principal: 1000000, rate: 9, months: 60 }, result: "Maturity: ₹15,60,162 | Interest: ₹5,60,162" },
    ],
    faqs: [
      { question: "How is FD interest calculated?", answer: "For compound interest FD: A = P × (1 + r/n)^(nt). Where P=principal, r=annual rate/100, n=compounding frequency per year, t=years. For simple interest: A = P × (1 + r×t/100)." },
      { question: "Which bank gives highest FD rate in 2025?", answer: "Small finance banks offer highest rates: Unity SFB (9.5%), ESAF SFB (9.25%), Ujjivan SFB (8.75%). Major banks: SBI (7.1%), HDFC (7.4%), ICICI (7.2%). All are DICGC insured up to ₹5L." },
      { question: "Is FD interest taxable?", answer: "Yes. FD interest is added to your income and taxed at your slab rate. TDS @10% is deducted if interest exceeds ₹40,000/year (₹50,000 for senior citizens). Submit Form 15G/15H to avoid TDS if income is below taxable limit." },
      { question: "What is the difference between cumulative and non-cumulative FD?", answer: "Cumulative FD: interest is reinvested and paid at maturity. Non-cumulative FD: interest is paid periodically (monthly/quarterly). Cumulative gives higher maturity due to compounding." },
      { question: "Can I break an FD before maturity?", answer: "Yes, with a premature withdrawal penalty of 0.5-1% on the applicable rate. Some banks offer no-penalty FDs or allow partial withdrawals. Liquid FDs (sweep-in) offer instant withdrawal with no penalty." },
    ],
    blogSlugs: ["what-is-fixed-deposit", "fd-interest-calculation", "best-fd-rates-2025", "fd-vs-recurring-deposit", "tax-on-fd-interest"],
  },
  {
    slug: "rd-calculator",
    name: "RD Calculator",
    shortName: "RD",
    description: "Calculate Recurring Deposit maturity amount and returns",
    icon: "rd",
    category: "banking",
    formula: "M = R × [(1+i)^n − 1] / (1 − (1+i)^(-1/3))",
    h1: "RD Calculator India 2025 — Recurring Deposit Maturity Calculator",
    intro: "Calculate your Recurring Deposit maturity amount and total interest earned. Compare RD returns across different banks and tenures instantly.",
    howItWorks: "Enter monthly deposit amount, annual interest rate, and tenure. The calculator uses the RD compound interest formula to show exact maturity value.",
    fields: [
      { label: "Monthly Deposit (₹)", type: "number", placeholder: "e.g. 5000" },
      { label: "Annual Interest Rate (%)", type: "number", placeholder: "e.g. 7" },
      { label: "Tenure (Months)", type: "number", placeholder: "e.g. 12" },
    ],
    examples: [
      { label: "₹5,000/month at 7% for 1 year", inputs: { monthly: 5000, rate: 7, months: 12 }, result: "Maturity: ₹62,204 | Interest: ₹2,204 | Invested: ₹60,000" },
      { label: "₹10,000/month at 7.5% for 3 years", inputs: { monthly: 10000, rate: 7.5, months: 36 }, result: "Maturity: ₹3,97,467 | Interest: ₹37,467 | Invested: ₹3,60,000" },
      { label: "₹2,000/month at 6.5% for 5 years", inputs: { monthly: 2000, rate: 6.5, months: 60 }, result: "Maturity: ₹1,42,136 | Interest: ₹22,136 | Invested: ₹1,20,000" },
    ],
    faqs: [
      { question: "What is Recurring Deposit?", answer: "RD is a bank savings scheme where you deposit a fixed amount monthly for a set period and earn compound interest. It's like a disciplined savings plan with guaranteed returns." },
      { question: "Is RD better than FD?", answer: "RD is better if you want to save monthly from salary. FD is better if you have a lump sum. Both offer the same interest rate for the same tenure at the same bank. FD earns more total interest as full amount earns from day one." },
      { question: "Is RD interest taxable?", answer: "Yes. RD interest is taxable as income from other sources at your slab rate. TDS @10% applies if interest exceeds ₹40,000/year. Submit Form 15G/15H to avoid TDS if applicable." },
      { question: "Can I withdraw RD before maturity?", answer: "Yes, premature withdrawal is allowed with a 1% penalty on the interest rate. Some banks may not allow partial withdrawal — you may need to close the entire RD." },
      { question: "What is the minimum RD amount?", answer: "Most banks allow RD from ₹100/month. Post Office RD minimum is ₹100/month. There's no maximum limit, but DICGC insurance covers up to ₹5L (principal + interest) per bank." },
    ],
    blogSlugs: ["what-is-recurring-deposit", "rd-vs-fd-comparison", "best-rd-rates-india", "post-office-rd-guide", "rd-tax-treatment"],
  },
  {
    slug: "ppf-calculator",
    name: "PPF Calculator",
    shortName: "PPF",
    description: "Calculate PPF maturity amount and tax-free returns",
    icon: "ppf",
    category: "investment",
    formula: "F = P × [((1+i)^n − 1) / i]",
    h1: "PPF Calculator India 2025 — Public Provident Fund Calculator",
    intro: "Calculate your PPF (Public Provident Fund) maturity amount at the current rate of 7.1% p.a. Get year-by-year balance projection and understand the EEE tax benefit.",
    howItWorks: "Enter annual PPF deposit amount and tenure (minimum 15 years). The calculator applies the current 7.1% annual interest rate and shows year-wise balance with tax-free maturity amount.",
    fields: [
      { label: "Annual Deposit (₹)", type: "number", placeholder: "e.g. 150000" },
      { label: "Current Interest Rate (%)", type: "number", placeholder: "7.1" },
      { label: "Tenure (Years)", type: "number", placeholder: "15" },
    ],
    examples: [
      { label: "₹1.5L/year for 15 years at 7.1%", inputs: { annual: 150000, rate: 7.1, years: 15 }, result: "Invested: ₹22.5L | Maturity: ₹40.68L | Tax-Free Gain: ₹18.18L" },
      { label: "₹1L/year for 20 years at 7.1%", inputs: { annual: 100000, rate: 7.1, years: 20 }, result: "Invested: ₹20L | Maturity: ₹43.13L | Tax-Free Gain: ₹23.13L" },
      { label: "₹1.5L/year for 25 years at 7.1%", inputs: { annual: 150000, rate: 7.1, years: 25 }, result: "Invested: ₹37.5L | Maturity: ₹1.03Cr | Tax-Free Gain: ₹65.5L" },
    ],
    faqs: [
      { question: "What is the current PPF interest rate?", answer: "The PPF interest rate for Q1 FY 2025-26 is 7.1% per annum, compounded annually. The government reviews and announces rates quarterly. To maximise interest, deposit before the 5th of each month." },
      { question: "What is the PPF lock-in period?", answer: "PPF has a mandatory 15-year lock-in period. After maturity, you can extend in 5-year blocks (with or without contributions). Partial withdrawal is allowed from the 7th year onwards." },
      { question: "What is EEE status of PPF?", answer: "PPF has EEE (Exempt-Exempt-Exempt) tax status: 1) Investment qualifies for 80C deduction (up to ₹1.5L), 2) Interest earned is tax-free, 3) Maturity amount is completely tax-free. This makes PPF one of the best tax-efficient instruments." },
      { question: "What is the maximum PPF deposit?", answer: "Maximum ₹1,50,000 per financial year per account. Minimum ₹500/year. You can deposit in lump sum or up to 12 instalments. Deposits above ₹1.5L do not earn interest and are returned without benefit." },
      { question: "Can NRI open PPF account?", answer: "No. NRIs cannot open a new PPF account. If a resident becomes NRI, the existing account can continue till maturity but no fresh extension is allowed. NRIs should consider NRE FD as an alternative." },
    ],
    blogSlugs: ["ppf-account-guide", "ppf-vs-elss", "ppf-withdrawal-rules", "ppf-extension-after-15-years", "ppf-tax-benefits"],
  },
  {
    slug: "nps-calculator",
    name: "NPS Calculator",
    shortName: "NPS",
    description: "Calculate NPS corpus and monthly pension at retirement",
    icon: "nps",
    category: "investment",
    formula: "Corpus = P × [(1+r)^n − 1] / r | Pension = Corpus × annuity rate / 12",
    h1: "NPS Calculator India 2025 — National Pension System Calculator",
    intro: "Calculate your NPS (National Pension System) retirement corpus and estimated monthly pension. See how much you need to invest monthly to achieve your retirement goal.",
    howItWorks: "Enter monthly NPS contribution, expected return rate, current age, and retirement age. The calculator projects your corpus and estimates monthly pension based on 6% annuity rate.",
    fields: [
      { label: "Monthly Contribution (₹)", type: "number", placeholder: "e.g. 5000" },
      { label: "Current Age (Years)", type: "number", placeholder: "e.g. 30" },
      { label: "Retirement Age (Years)", type: "number", placeholder: "60" },
      { label: "Expected Return (%)", type: "number", placeholder: "e.g. 10" },
    ],
    examples: [
      { label: "₹5,000/month from age 30 to 60 at 10%", inputs: { monthly: 5000, age: 30, retirement: 60, rate: 10 }, result: "Corpus: ₹1.13Cr | Lump Sum (60%): ₹67.7L | Monthly Pension: ₹27,000" },
      { label: "₹10,000/month from age 25 to 60 at 10%", inputs: { monthly: 10000, age: 25, retirement: 60, rate: 10 }, result: "Corpus: ₹3.82Cr | Lump Sum: ₹2.29Cr | Monthly Pension: ₹91,000" },
      { label: "₹2,000/month from age 35 to 60 at 10%", inputs: { monthly: 2000, age: 35, retirement: 60, rate: 10 }, result: "Corpus: ₹26.5L | Lump Sum: ₹15.9L | Monthly Pension: ₹6,300" },
    ],
    faqs: [
      { question: "How much tax can I save with NPS?", answer: "Old regime: Up to ₹2L deduction — ₹1.5L under 80CCD(1) within 80C limit + additional ₹50,000 under 80CCD(1B). At 30% slab this saves ₹62,400/year. Employer NPS contribution up to 10% of basic is deductible under 80CCD(2) with no cap." },
      { question: "What is the NPS withdrawal rule at 60?", answer: "At 60: minimum 40% must go to annuity (for regular pension), up to 60% can be withdrawn as tax-free lump sum. If total corpus is ≤₹5L, full amount can be withdrawn. Early exit: 80% annuity, 20% lump sum." },
      { question: "Which NPS fund manager is best?", answer: "Top performers (10-year Equity/E fund CAGR): HDFC Pension ~12.8%, SBI Pension ~12.5%, ICICI Prudential ~12.3%, Kotak ~12.1%. Performance varies by year. Choose based on long-term track record." },
      { question: "Can I invest in both NPS and PPF?", answer: "Yes, absolutely. NPS and PPF serve different purposes and can both be maximised. PPF (₹1.5L) for guaranteed tax-free returns + NPS Tier 1 (₹50,000 extra deduction) for equity-linked pension. Combined tax saving: up to ₹62,400/year." },
      { question: "What is the difference between Tier 1 and Tier 2 NPS?", answer: "Tier 1: Mandatory pension account. Locked till 60 (with partial withdrawal conditions). Tax benefits available. Minimum ₹1,000/year. Tier 2: Voluntary savings. Withdraw anytime. No tax benefits (except for government employees). Minimum ₹250." },
    ],
    blogSlugs: ["nps-pension-guide", "nps-tax-benefits-80ccd", "nps-vs-ppf", "nps-fund-manager-comparison", "nps-withdrawal-rules"],
  },
  {
    slug: "home-loan-calculator",
    name: "Home Loan Calculator",
    shortName: "Home Loan",
    description: "Calculate home loan EMI, total interest, and amortisation",
    icon: "home",
    category: "loan",
    formula: "EMI = P × r × (1+r)^n / [(1+r)^n − 1]",
    h1: "Home Loan EMI Calculator India 2025 — Housing Loan Calculator",
    intro: "Calculate your home loan EMI, total interest payable, and full amortisation schedule. Compare different tenures and see exactly how much interest you save by prepaying.",
    howItWorks: "Enter home loan amount, interest rate, and tenure. See monthly EMI, total interest, total payment, and year-wise amortisation table.",
    fields: [
      { label: "Loan Amount (₹)", type: "number", placeholder: "e.g. 5000000" },
      { label: "Interest Rate (% p.a.)", type: "number", placeholder: "e.g. 8.5" },
      { label: "Tenure (Years)", type: "number", placeholder: "e.g. 20" },
    ],
    examples: [
      { label: "₹50L at 8.5% for 20 years", inputs: { amount: 5000000, rate: 8.5, years: 20 }, result: "EMI: ₹43,391 | Total Interest: ₹54.1L | Total: ₹1.04Cr" },
      { label: "₹30L at 8.75% for 15 years", inputs: { amount: 3000000, rate: 8.75, years: 15 }, result: "EMI: ₹29,890 | Total Interest: ₹23.8L | Total: ₹53.8L" },
      { label: "₹1Cr at 9% for 30 years", inputs: { amount: 10000000, rate: 9, years: 30 }, result: "EMI: ₹80,462 | Total Interest: ₹1.9Cr | Total: ₹2.9Cr" },
    ],
    faqs: [
      { question: "What is the current home loan interest rate in India?", answer: "Home loan rates in 2025: SBI 8.50-9.15%, HDFC Bank 8.70-9.35%, ICICI Bank 8.75-9.30%, Bank of Baroda 8.40-9.00%. Rates are floating and linked to repo rate (RLLR). Best rates go to those with CIBIL score 750+." },
      { question: "What is the tax benefit on home loan?", answer: "Two benefits under old regime: 1) Section 24(b): interest deduction up to ₹2L for self-occupied property, unlimited for let-out. 2) Section 80C: principal repayment counts within ₹1.5L 80C limit. Both unavailable in new tax regime." },
      { question: "How much home loan can I get on my salary?", answer: "Rule of thumb: banks offer 60× net monthly salary (20-year tenure). Salary ₹50,000 → loan up to ₹30L. Salary ₹1L → up to ₹60L. FOIR (existing EMIs) reduces eligibility. CIBIL 750+ gets maximum eligibility." },
      { question: "What is the down payment required for home loan?", answer: "RBI mandates: LTV (Loan to Value) ratio maximum 90% for loans up to ₹30L, 80% for ₹30-75L, 75% for above ₹75L. So minimum down payment: 10% for loans up to ₹30L, 20% for ₹30-75L, 25% above ₹75L." },
      { question: "Should I opt for fixed or floating rate home loan?", answer: "Floating rate is currently 1-1.5% cheaper and has no prepayment penalty (RBI mandated). Fixed rates give certainty but cost more. In a falling interest rate environment (like now), floating rate is generally better." },
    ],
    blogSlugs: ["home-loan-guide-india", "home-loan-tax-benefits", "how-to-get-lowest-home-loan-rate", "home-loan-prepayment-strategy", "pmay-home-loan-subsidy"],
  },
  {
    slug: "personal-loan-calculator",
    name: "Personal Loan Calculator",
    shortName: "Personal Loan",
    description: "Calculate personal loan EMI and total interest cost",
    icon: "personal-loan",
    category: "loan",
    formula: "EMI = P × r × (1+r)^n / [(1+r)^n − 1]",
    h1: "Personal Loan EMI Calculator India 2025",
    intro: "Calculate personal loan EMI and total cost instantly. Compare interest rates across lenders and find the most affordable personal loan for your needs.",
    howItWorks: "Enter loan amount, interest rate, and tenure in months. Get EMI, total interest payable, and total repayment amount. Adjust inputs to compare different loan options.",
    fields: [
      { label: "Loan Amount (₹)", type: "number", placeholder: "e.g. 500000" },
      { label: "Interest Rate (% p.a.)", type: "number", placeholder: "e.g. 12" },
      { label: "Tenure (Months)", type: "number", placeholder: "e.g. 36" },
    ],
    examples: [
      { label: "₹5L at 12% for 3 years", inputs: { amount: 500000, rate: 12, months: 36 }, result: "EMI: ₹16,607 | Total Interest: ₹97,852 | Total: ₹5,97,852" },
      { label: "₹2L at 14% for 2 years", inputs: { amount: 200000, rate: 14, months: 24 }, result: "EMI: ₹9,613 | Total Interest: ₹30,712 | Total: ₹2,30,712" },
      { label: "₹10L at 10.5% for 5 years", inputs: { amount: 1000000, rate: 10.5, months: 60 }, result: "EMI: ₹21,494 | Total Interest: ₹2,89,640 | Total: ₹12,89,640" },
    ],
    faqs: [
      { question: "What is the interest rate for personal loan in India 2025?", answer: "Personal loan rates range from 10.49% (SBI Xpress Credit) to 24%+ for unsecured loans. HDFC Bank: 10.75-21%, ICICI Bank: 10.65-16%, Bajaj Finserv: 11-35%, digital lenders: 12-30%. Rate depends on CIBIL score, income, and employer." },
      { question: "What is the minimum CIBIL score for personal loan?", answer: "Most banks require minimum CIBIL 700. 750+ gets best rates. 700-749: loan approved at higher rate. Below 700: likely rejection or very high rate (18%+). No-credit-history applicants can get loans at higher rates from NBFCs." },
      { question: "What documents are needed for personal loan?", answer: "KYC: PAN, Aadhaar. Income: last 3 months salary slips + 6 months bank statements (salaried). For self-employed: 2 years IT returns, bank statements, GST registration. Some lenders offer instant pre-approved loans with just Aadhaar+PAN." },
      { question: "Can I get personal loan without salary slip?", answer: "Yes. Self-employed can get personal loans using IT returns. Bank statement loans (12 months turnover). NBFCs and fintech lenders (Navi, KreditBee, MoneyView) offer loans based on cash flow analysis without traditional documents." },
      { question: "What is the maximum personal loan amount in India?", answer: "Most banks: up to ₹40L. HDFC Bank: up to ₹40L, SBI: up to ₹20L, ICICI: up to ₹50L. Amount depends on income, CIBIL score, and existing obligations. Maximum is typically 10-15× net monthly income." },
    ],
    blogSlugs: ["personal-loan-guide-india", "personal-loan-interest-rates-2025", "personal-loan-vs-credit-card", "how-to-reduce-personal-loan-interest", "personal-loan-prepayment-calculator"],
  },
  {
    slug: "car-loan-calculator",
    name: "Car Loan Calculator",
    shortName: "Car Loan",
    description: "Calculate car loan EMI for new and used vehicles",
    icon: "car",
    category: "loan",
    formula: "EMI = P × r × (1+r)^n / [(1+r)^n − 1]",
    h1: "Car Loan EMI Calculator India 2025 — Auto Loan Calculator",
    intro: "Calculate your car loan EMI and total interest cost for any vehicle. Compare financing options and choose the optimal down payment and tenure combination.",
    howItWorks: "Enter car loan amount (on-road price minus down payment), interest rate, and tenure. Get monthly EMI, total interest, and total amount payable.",
    fields: [
      { label: "Loan Amount (₹)", type: "number", placeholder: "e.g. 800000" },
      { label: "Interest Rate (% p.a.)", type: "number", placeholder: "e.g. 9" },
      { label: "Tenure (Months)", type: "number", placeholder: "e.g. 60" },
    ],
    examples: [
      { label: "₹8L at 9% for 5 years", inputs: { amount: 800000, rate: 9, months: 60 }, result: "EMI: ₹16,607 | Total Interest: ₹1,96,420 | Total: ₹9,96,420" },
      { label: "₹5L at 8.5% for 3 years", inputs: { amount: 500000, rate: 8.5, months: 36 }, result: "EMI: ₹15,775 | Total Interest: ₹67,900 | Total: ₹5,67,900" },
      { label: "₹15L at 9.5% for 7 years", inputs: { amount: 1500000, rate: 9.5, months: 84 }, result: "EMI: ₹24,200 | Total Interest: ₹5,32,800 | Total: ₹20,32,800" },
    ],
    faqs: [
      { question: "What is the current car loan interest rate in India?", answer: "Car loan rates 2025: SBI 8.85-9.85%, HDFC Bank 9.25-10.25%, ICICI Bank 9.00-10.00%, Axis Bank 9.25-10.50%. New cars get lower rates than used cars. Used car loans: 10-15%. Electric vehicle loans get special rates from some banks." },
      { question: "What is the maximum car loan tenure?", answer: "Most banks offer car loans up to 7 years (84 months) for new cars. Used car loans: up to 5 years. Longer tenure reduces EMI but significantly increases total interest. Most financial advisors recommend 3-5 years for optimal cost." },
      { question: "How much down payment is required for car loan?", answer: "Typical car loan LTV: 80-90% of ex-showroom price. Minimum down payment: 10-20% of ex-showroom price. Plus registration, insurance, and accessories are typically funded separately. Higher down payment → lower EMI and interest." },
      { question: "Can I get a car loan without income proof?", answer: "Difficult but possible. Options: secure car loan against FD or property (asset-backed), add co-applicant with income, show bank statement cash flows. NBFCs are more flexible than banks for self-employed or informal income earners." },
      { question: "What is the foreclosure charge on car loan?", answer: "Car loan foreclosure charges: SBI nil (floating rate), HDFC Bank 5% in year 1, nil after 1 year. ICICI Bank: 5% in years 1-2, nil thereafter. Always check your specific loan agreement for the exact prepayment terms." },
    ],
    blogSlugs: ["car-loan-guide-india", "car-loan-vs-own-funds", "best-car-loan-rates-2025", "car-loan-for-self-employed", "electric-vehicle-loan-india"],
  },
  {
    slug: "salary-calculator",
    name: "Salary Calculator",
    shortName: "Salary",
    description: "Calculate in-hand salary from CTC with all deductions",
    icon: "salary",
    category: "payroll",
    formula: "In-Hand = Gross Salary − TDS − Employee PF − Professional Tax",
    h1: "Salary Calculator India 2025 — CTC to In-Hand Salary Calculator",
    intro: "Calculate your exact monthly in-hand salary from CTC. Get a complete salary breakup including basic, HRA, allowances, PF deduction, TDS, and net take-home pay.",
    howItWorks: "Enter your annual CTC. The calculator assumes standard salary structure (40% basic, 50% of basic as HRA for metro) and computes all deductions to give you accurate take-home salary.",
    fields: [
      { label: "Annual CTC (₹)", type: "number", placeholder: "e.g. 1200000" },
      { label: "City Type", type: "select", options: ["Metro (Delhi/Mumbai/Chennai/Kolkata)", "Non-Metro"] },
      { label: "Tax Regime", type: "select", options: ["New Tax Regime", "Old Tax Regime"] },
    ],
    examples: [
      { label: "₹12L CTC, Metro, New Regime", inputs: { ctc: 1200000, city: "metro", regime: "new" }, result: "In-Hand: ₹86,500/month | TDS: ₹4,167/month | PF: ₹4,800/month" },
      { label: "₹6L CTC, Non-Metro, New Regime", inputs: { ctc: 600000, city: "non-metro", regime: "new" }, result: "In-Hand: ₹46,200/month | TDS: ₹0/month | PF: ₹2,400/month" },
      { label: "₹24L CTC, Metro, Old Regime", inputs: { ctc: 2400000, city: "metro", regime: "old" }, result: "In-Hand: ₹1,58,000/month | TDS: ₹25,000/month | PF: ₹9,600/month" },
    ],
    faqs: [
      { question: "What is the difference between CTC and in-hand salary?", answer: "CTC (Cost to Company) includes employer PF contribution, gratuity provision, and all benefits. In-hand = Gross Salary − Employee PF (12% of basic) − TDS − Professional Tax. Typically in-hand is 65-75% of CTC." },
      { question: "How is TDS calculated on salary?", answer: "Employer estimates annual taxable income → applies income tax as per slab → divides by 12 for monthly TDS. For new regime FY 2025-26: ₹0-3L nil, ₹3-7L 5%, ₹7-10L 10%, ₹10-12L 15%, ₹12-15L 20%, above ₹15L 30%. Plus 4% cess." },
      { question: "How much PF is deducted from salary?", answer: "Employee PF = 12% of Basic Salary. Employer PF = 12% of Basic (3.67% to EPF, 8.33% to EPS). Both calculated on basic salary subject to ₹15,000 wage ceiling for mandatory contribution. For salary above ₹15,000, contributions on actual salary." },
      { question: "What is professional tax and how much is it?", answer: "Professional tax is a state levy on salary. Maharashtra: ₹200/month (₹2,400/year). Karnataka: ₹200/month. West Bengal: up to ₹200/month. Not all states have professional tax. It's deductible from taxable income (old regime)." },
      { question: "How can I increase my in-hand salary legally?", answer: "Restructure salary: optimise basic (lower basic = lower PF if that suits you), claim HRA for rent paid, use flexible benefit plan (meal coupons, NPS), increase employer NPS contribution (not counted in most CTC calculations, saves tax under 80CCD(2))." },
    ],
    blogSlugs: ["ctc-vs-in-hand-salary", "salary-components-india", "how-to-increase-take-home-salary", "salary-restructuring-tax-savings", "salary-negotiation-guide"],
  },
  {
    slug: "income-tax-calculator",
    name: "Income Tax Calculator 2025-26",
    shortName: "Income Tax",
    description: "Calculate income tax under new and old tax regime 2025-26",
    icon: "tax",
    category: "tax",
    formula: "Tax = (Income − Deductions) × Slab Rate + 4% Cess",
    h1: "Income Tax Calculator FY 2025-26 — New vs Old Regime",
    intro: "Calculate your income tax for FY 2025-26 under both new and old tax regime. Get a side-by-side comparison to choose the regime that saves you the most tax.",
    howItWorks: "Enter gross income, investments (80C, 80D, NPS), and allowances (HRA, LTA). The calculator computes tax under both regimes so you can compare and choose wisely.",
    fields: [
      { label: "Annual Gross Income (₹)", type: "number", placeholder: "e.g. 1000000" },
      { label: "80C Investments (₹)", type: "number", placeholder: "e.g. 150000" },
      { label: "80D Health Insurance (₹)", type: "number", placeholder: "e.g. 25000" },
      { label: "HRA Exempt (₹)", type: "number", placeholder: "e.g. 120000" },
    ],
    examples: [
      { label: "₹10L income, full deductions (old regime)", inputs: { income: 1000000, deductions: 350000 }, result: "Old Regime Tax: ₹54,600 | New Regime Tax: ₹54,600 | Breakeven point" },
      { label: "₹15L income, minimal deductions", inputs: { income: 1500000, deductions: 75000 }, result: "Old Regime: ₹1,87,200 | New Regime: ₹1,17,000 | New regime saves ₹70,200" },
      { label: "₹8L income, full 80C + HRA + 80D", inputs: { income: 800000, deductions: 300000 }, result: "Old Regime: ₹25,480 | New Regime: ₹31,200 | Old regime saves ₹5,720" },
    ],
    faqs: [
      { question: "What are the new tax regime slabs for FY 2025-26?", answer: "₹0-3L: Nil. ₹3-7L: 5%. ₹7-10L: 10%. ₹10-12L: 15%. ₹12-15L: 20%. Above ₹15L: 30%. Plus 4% health & education cess. Standard deduction ₹75,000 available. Rebate u/s 87A: nil tax if income ≤₹7L (new regime)." },
      { question: "Which tax regime is better for ₹10L income?", answer: "For ₹10L income, it depends on deductions: If total deductions (80C+HRA+80D+home loan) exceed ₹3.25L, old regime is better. Below ₹3.25L deductions, new regime wins. Use our calculator to check your specific situation." },
      { question: "Can I switch between old and new tax regime?", answer: "Salaried employees can switch every year by declaring their choice to employer at the start of FY. Self-employed/business owners can switch to old regime only once and then must stay. New regime is default — no declaration needed to stay in new regime." },
      { question: "What is Section 87A rebate?", answer: "Under new regime: 100% tax rebate (no tax) if total income ≤₹7L. Under old regime: rebate up to ₹12,500 if income ≤₹5L. For new regime, even if income is ₹7L, zero tax — but ₹7.5L income will pay tax on full ₹7.5L amount." },
      { question: "What deductions are allowed in new tax regime?", answer: "New regime allows very few deductions: Standard deduction ₹75,000, employer NPS under 80CCD(2), Agniveer Corpus Fund 80CCH, Section 57(iia) family pension, and a few others. No 80C, HRA, 80D, or home loan interest deduction." },
    ],
    blogSlugs: ["new-vs-old-tax-regime", "income-tax-slabs-2025-26", "section-87a-rebate-guide", "income-tax-deductions-list", "how-to-file-itr-online"],
  },
  {
    slug: "lumpsum-calculator",
    name: "Lump Sum Calculator",
    shortName: "Lump Sum",
    description: "Calculate lump sum investment returns and future value",
    icon: "lumpsum",
    category: "investment",
    formula: "FV = PV × (1 + r)^n",
    h1: "Lump Sum Calculator India 2025 — One-Time Investment Return Calculator",
    intro: "Calculate how a one-time lump sum investment grows over time. Compare different investment options and see the impact of compounding on your wealth.",
    howItWorks: "Enter investment amount, expected annual return rate, and investment period. The calculator shows future value, total gain, and CAGR for your investment.",
    fields: [
      { label: "Investment Amount (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Expected Annual Return (%)", type: "number", placeholder: "e.g. 12" },
      { label: "Investment Period (Years)", type: "number", placeholder: "e.g. 10" },
    ],
    examples: [
      { label: "₹1L at 12% for 10 years", inputs: { amount: 100000, rate: 12, years: 10 }, result: "Future Value: ₹3,10,585 | Gain: ₹2,10,585 | CAGR: 12%" },
      { label: "₹5L at 15% for 15 years", inputs: { amount: 500000, rate: 15, years: 15 }, result: "Future Value: ₹40,91,313 | Gain: ₹35,91,313 | CAGR: 15%" },
      { label: "₹10L at 10% for 20 years", inputs: { amount: 1000000, rate: 10, years: 20 }, result: "Future Value: ₹67,27,500 | Gain: ₹57,27,500 | CAGR: 10%" },
    ],
    faqs: [
      { question: "Is lump sum or SIP better?", answer: "Lump sum is better when markets are at a low (you invest all at the bottom). SIP is better when markets are volatile or at a high (rupee-cost averaging reduces risk). For most retail investors, SIP is recommended as it eliminates timing risk." },
      { question: "What is CAGR?", answer: "CAGR (Compound Annual Growth Rate) is the rate at which an investment grows annually to reach the final value. CAGR = [(Final Value / Initial Value)^(1/years) − 1] × 100. It's the best way to compare investments of different durations." },
      { question: "What return should I use for lump sum calculator?", answer: "Equity mutual funds: 10-12% (Nifty 50 historical). Debt funds: 6-8%. Gold: 8-10%. PPF: 7.1% (current). FD: 7-9.5% (varies by bank). Real estate: 8-12% (highly variable by location). Use conservative estimates for planning." },
      { question: "How does compounding frequency affect returns?", answer: "More frequent compounding = higher effective returns. Annual compounding at 12%: ₹1L → ₹3.1L in 10 years. Monthly compounding at 12%: ₹1L → ₹3.3L. Daily compounding: ₹1L → ₹3.32L. The difference grows significantly over longer periods." },
      { question: "What is the Rule of 72?", answer: "Rule of 72: divide 72 by the annual return rate to find years to double. At 12%: 72/12 = 6 years to double. At 8%: 9 years. At 6%: 12 years. Quick mental math tool for estimating investment doubling time." },
    ],
    blogSlugs: ["lump-sum-vs-sip", "how-to-invest-lump-sum", "best-lump-sum-investments-india", "compounding-power-of-investing", "cagr-meaning-explained"],
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    shortName: "Compound Interest",
    description: "Calculate compound interest for any principal, rate, and period",
    icon: "compound",
    category: "finance",
    formula: "A = P × (1 + r/n)^(n×t)",
    h1: "Compound Interest Calculator India 2025",
    intro: "Calculate compound interest for any investment or loan. Understand how your money grows exponentially over time with the power of compounding.",
    howItWorks: "Enter principal, annual interest rate, compounding frequency, and time period. Get the final amount and total interest earned with year-by-year growth.",
    fields: [
      { label: "Principal Amount (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Annual Rate (%)", type: "number", placeholder: "e.g. 10" },
      { label: "Time Period (Years)", type: "number", placeholder: "e.g. 10" },
      { label: "Compounding Frequency", type: "select", options: ["Annually", "Semi-Annually", "Quarterly", "Monthly", "Daily"] },
    ],
    examples: [
      { label: "₹1L at 10% annually for 10 years", inputs: { principal: 100000, rate: 10, years: 10 }, result: "Amount: ₹2,59,374 | Interest: ₹1,59,374" },
      { label: "₹1L at 10% monthly for 10 years", inputs: { principal: 100000, rate: 10, years: 10 }, result: "Amount: ₹2,70,704 | Interest: ₹1,70,704 | Extra vs annual: ₹11,330" },
      { label: "₹5L at 8% quarterly for 5 years", inputs: { principal: 500000, rate: 8, years: 5 }, result: "Amount: ₹7,42,974 | Interest: ₹2,42,974" },
    ],
    faqs: [
      { question: "What is compound interest?", answer: "Compound interest is interest calculated on both the initial principal and all accumulated interest from previous periods. Einstein called it the 'eighth wonder of the world'. The longer you invest, the more dramatic the compounding effect." },
      { question: "What is the difference between simple and compound interest?", answer: "Simple interest: calculated only on principal. ₹1L at 10% for 10 years = ₹2L. Compound interest (annual): calculated on principal + accumulated interest. ₹1L at 10% for 10 years = ₹2,59,374. Compound interest is always higher." },
      { question: "Which investments use compound interest in India?", answer: "PPF (7.1% annually), EPF (8.25%), NPS (market-linked), Mutual Fund SIP (market-linked), FD/RD (quarterly compounding), NSC (annual compounding), Sukanya Samriddhi (8.2% annually). All these grow your wealth through compounding." },
      { question: "How does compounding frequency affect returns?", answer: "The more frequently interest compounds, the higher the effective annual yield (EAY). 12% nominal: Annual EAY = 12.00%, Quarterly = 12.55%, Monthly = 12.68%, Daily = 12.75%. The difference becomes significant over 10+ years." },
      { question: "What is the power of starting early?", answer: "₹1L invested at age 25 at 12% = ₹93.1L at 65. Same ₹1L at age 35 = ₹29.96L at 65. Starting 10 years earlier gives 3× more wealth! This is why financial advisors always say 'start investing as early as possible'." },
    ],
    blogSlugs: ["compound-interest-explained", "simple-vs-compound-interest", "power-of-compounding-india", "compound-interest-investments", "start-investing-early-benefits"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    shortName: "ROI",
    description: "Calculate Return on Investment for business and personal finance",
    icon: "roi",
    category: "business",
    formula: "ROI = (Net Profit / Cost of Investment) × 100",
    h1: "ROI Calculator India — Return on Investment Calculator",
    intro: "Calculate ROI (Return on Investment) for any business decision, investment, or project. Get annualised ROI and compare multiple investment options easily.",
    howItWorks: "Enter the initial investment cost and final value (or net profit). The calculator computes ROI percentage and annualised ROI for easy comparison across investments.",
    fields: [
      { label: "Initial Investment (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Final Value / Returns (₹)", type: "number", placeholder: "e.g. 150000" },
      { label: "Investment Period (Years)", type: "number", placeholder: "e.g. 2" },
    ],
    examples: [
      { label: "₹1L investment, returned ₹1.5L in 2 years", inputs: { investment: 100000, returns: 150000, years: 2 }, result: "ROI: 50% | Annualised ROI: 22.5% | Net Profit: ₹50,000" },
      { label: "₹5L business investment, ₹8L return in 3 years", inputs: { investment: 500000, returns: 800000, years: 3 }, result: "ROI: 60% | Annualised ROI: 17% | Net Profit: ₹3L" },
      { label: "₹10L real estate, ₹18L after 5 years", inputs: { investment: 1000000, returns: 1800000, years: 5 }, result: "ROI: 80% | Annualised ROI: 12.5% | Net Profit: ₹8L" },
    ],
    faqs: [
      { question: "What is ROI?", answer: "ROI (Return on Investment) measures how much profit you earn relative to the cost. ROI = (Net Profit / Cost) × 100. A 50% ROI means you earned ₹50 for every ₹100 invested. Higher ROI = better investment performance." },
      { question: "What is a good ROI in India?", answer: "Context-dependent: Equity mutual funds: 12-15% p.a. considered good. Real estate: 8-12% p.a. FD: 7-9.5% p.a. Business investment: 20%+ for good businesses. Benchmark against cost of capital (~12-15% for most Indian businesses)." },
      { question: "What is the difference between ROI and CAGR?", answer: "ROI measures total return without considering time. CAGR measures the smoothed annual growth rate. Example: 50% ROI over 2 years = 22.47% CAGR. Always use CAGR (annualised ROI) when comparing investments of different durations." },
      { question: "How do I calculate ROI for a business?", answer: "Business ROI = (Annual Net Profit / Total Investment) × 100. Include all costs: capital investment, operating expenses, overheads. Example: ₹10L invested, ₹2L annual profit → ROI = 20% p.a. Compare against cost of capital to assess viability." },
      { question: "What is negative ROI?", answer: "Negative ROI means you lost money. ROI = -20% means you lost ₹20 for every ₹100 invested. Causes: poor investment choice, market downturn, business failure. Acceptable in early-stage businesses but not sustainable long-term." },
    ],
    blogSlugs: ["roi-calculator-guide", "what-is-roi-business", "roi-vs-cagr", "marketing-roi-calculation", "business-investment-roi"],
  },
  {
    slug: "margin-calculator",
    name: "Profit Margin Calculator",
    shortName: "Margin",
    description: "Calculate gross, net, and operating profit margin for business",
    icon: "margin",
    category: "business",
    formula: "Profit Margin = (Profit / Revenue) × 100",
    h1: "Profit Margin Calculator India — Gross & Net Margin Calculator",
    intro: "Calculate gross profit margin, net profit margin, and markup percentage for your business. Essential for pricing decisions and business profitability analysis.",
    howItWorks: "Enter revenue and cost figures. The calculator computes gross margin, net margin, markup, and profit amount. Adjust to find the right pricing for your target margin.",
    fields: [
      { label: "Selling Price / Revenue (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Cost of Goods Sold (₹)", type: "number", placeholder: "e.g. 60000" },
      { label: "Operating Expenses (₹)", type: "number", placeholder: "e.g. 20000" },
    ],
    examples: [
      { label: "Revenue ₹1L, COGS ₹60K, OpEx ₹20K", inputs: { revenue: 100000, cogs: 60000, opex: 20000 }, result: "Gross Margin: 40% | Net Margin: 20% | Gross Profit: ₹40K | Net Profit: ₹20K" },
      { label: "Revenue ₹5L, COGS ₹3L, OpEx ₹1L", inputs: { revenue: 500000, cogs: 300000, opex: 100000 }, result: "Gross Margin: 40% | Net Margin: 20% | Net Profit: ₹1L" },
      { label: "Revenue ₹10L, COGS ₹7L, OpEx ₹1.5L", inputs: { revenue: 1000000, cogs: 700000, opex: 150000 }, result: "Gross Margin: 30% | Net Margin: 15% | Net Profit: ₹1.5L" },
    ],
    faqs: [
      { question: "What is gross profit margin?", answer: "Gross Profit Margin = (Revenue − COGS) / Revenue × 100. It measures profitability before operating expenses. A 40% gross margin means for every ₹100 in sales, ₹40 remains after paying for goods/services." },
      { question: "What is a good profit margin in India?", answer: "Varies by industry: Retail: 5-15%. Manufacturing: 10-20%. Software/IT: 20-40%. Consulting: 25-50%. FMCG: 10-20%. SaaS: 60-80% (gross margin). Compare to industry benchmarks rather than absolute numbers." },
      { question: "What is the difference between margin and markup?", answer: "Margin = Profit / Selling Price × 100 (percentage of selling price). Markup = Profit / Cost × 100 (percentage of cost). If cost is ₹60 and sell at ₹100: Margin = 40%, Markup = 66.7%. Always specify which one you mean in business discussions." },
      { question: "How do I set the right selling price?", answer: "Selling price = Cost × (1 + Markup%). For desired 40% margin: Selling price = Cost / (1 − 0.40) = Cost × 1.667. Example: product costs ₹600, target 40% margin → sell at ₹1,000. Include all costs: material, labour, overhead, GST." },
      { question: "How does GST affect profit margin?", answer: "GST is generally not a cost for registered businesses (you collect from customer and pay net of ITC). However, if selling to unregistered consumers, the GST-inclusive price affects competitiveness. Always calculate margin on ex-GST revenue." },
    ],
    blogSlugs: ["profit-margin-guide", "how-to-improve-profit-margin", "gross-vs-net-margin", "pricing-strategy-india", "gst-and-profit-margin"],
  },
  {
    slug: "break-even-calculator",
    name: "Break Even Calculator",
    shortName: "Break Even",
    description: "Calculate break-even point in units and revenue for your business",
    icon: "breakeven",
    category: "business",
    formula: "Break-Even Units = Fixed Costs / (Selling Price − Variable Cost)",
    h1: "Break Even Calculator India — Business Break-Even Point Calculator",
    intro: "Calculate the break-even point for your business in units sold and revenue. Know exactly how many sales you need to cover all costs and start making profit.",
    howItWorks: "Enter fixed costs, variable cost per unit, and selling price per unit. The calculator gives break-even units, break-even revenue, and the margin of safety.",
    fields: [
      { label: "Fixed Costs per Month (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Variable Cost per Unit (₹)", type: "number", placeholder: "e.g. 200" },
      { label: "Selling Price per Unit (₹)", type: "number", placeholder: "e.g. 500" },
    ],
    examples: [
      { label: "Fixed ₹1L, Variable ₹200, Sell ₹500", inputs: { fixed: 100000, variable: 200, price: 500 }, result: "Break-even: 334 units | Break-even Revenue: ₹1,67,000/month" },
      { label: "Fixed ₹5L, Variable ₹1,000, Sell ₹2,500", inputs: { fixed: 500000, variable: 1000, price: 2500 }, result: "Break-even: 334 units | Break-even Revenue: ₹8,35,000/month" },
      { label: "Fixed ₹50K, Variable ₹50, Sell ₹200", inputs: { fixed: 50000, variable: 50, price: 200 }, result: "Break-even: 334 units | Break-even Revenue: ₹66,800/month" },
    ],
    faqs: [
      { question: "What is break-even point?", answer: "Break-even point is the level of sales at which total revenue equals total costs — zero profit, zero loss. Beyond this point, every unit sold generates profit. Formula: BEP (units) = Fixed Costs / Contribution Margin per unit." },
      { question: "What is contribution margin?", answer: "Contribution Margin = Selling Price − Variable Cost. It's the amount each unit contributes towards covering fixed costs and then profit. High contribution margin = easier to break even. Example: Sell ₹500, Variable cost ₹200 → Contribution ₹300." },
      { question: "How do I reduce my break-even point?", answer: "Three ways: 1) Reduce fixed costs (rent, salaries), 2) Reduce variable costs (negotiate better supplier prices), 3) Increase selling price (premium positioning). Reducing fixed costs has the most direct impact on break-even." },
      { question: "What is margin of safety?", answer: "Margin of Safety = Actual Sales − Break-even Sales. It shows how much sales can fall before reaching break-even. Example: Actual sales 500 units, BEP 334 units → MoS = 166 units (33%). Higher MoS = more business resilience." },
      { question: "Can break-even analysis apply to services?", answer: "Yes. For service businesses: Fixed costs (rent, salaries) / (Revenue per client − Variable cost per client). For a CA firm: Fixed costs ₹2L, Revenue per client ₹10K, Variable cost ₹2K → need 25 clients/month to break even." },
    ],
    blogSlugs: ["break-even-analysis-guide", "fixed-vs-variable-costs", "contribution-margin-explained", "how-to-reduce-break-even", "break-even-analysis-for-startups"],
  },
  {
    slug: "gst-profit-calculator",
    name: "Business Profit Calculator",
    shortName: "Profit Calc",
    description: "Calculate net profit after GST, expenses, and taxes",
    icon: "profit",
    category: "business",
    formula: "Net Profit = Revenue − COGS − Operating Expenses − GST − Tax",
    h1: "Business Profit Calculator India — Net Profit After GST & Tax",
    intro: "Calculate your business net profit after deducting GST, operating expenses, and income tax. Get a complete P&L summary for any business scenario.",
    howItWorks: "Enter total revenue, cost of goods sold, operating expenses, and GST rate. The calculator shows gross profit, net GST payable, and final profit after all deductions.",
    fields: [
      { label: "Total Revenue (₹)", type: "number", placeholder: "e.g. 500000" },
      { label: "Cost of Goods/Services (₹)", type: "number", placeholder: "e.g. 200000" },
      { label: "Operating Expenses (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "GST Rate (%)", type: "select", options: ["0%", "5%", "12%", "18%", "28%"] },
    ],
    examples: [
      { label: "Revenue ₹5L, COGS ₹2L, OpEx ₹1L, GST 18%", inputs: { revenue: 500000, cogs: 200000, opex: 100000, gst: 18 }, result: "Gross Profit: ₹3L | Net GST Payable: ₹36K | Net Profit Before Tax: ₹1.64L" },
      { label: "Revenue ₹10L, COGS ₹6L, OpEx ₹2L, GST 12%", inputs: { revenue: 1000000, cogs: 600000, opex: 200000, gst: 12 }, result: "Gross Profit: ₹4L | Net GST: ₹48K | Net Profit: ₹1.52L" },
      { label: "Revenue ₹20L, COGS ₹12L, OpEx ₹4L, GST 18%", inputs: { revenue: 2000000, cogs: 1200000, opex: 400000, gst: 18 }, result: "Gross Profit: ₹8L | Net GST: ₹72K | Net Profit: ₹3.28L" },
    ],
    faqs: [
      { question: "Is GST included in business revenue?", answer: "No. For accounting and tax purposes, revenue is reported excluding GST (because GST collected is a liability payable to the government). Profit margins are calculated on ex-GST revenue." },
      { question: "How does ITC reduce my GST cost?", answer: "GST paid on purchases (ITC) is deducted from GST collected on sales. Net GST = Output GST − Input Tax Credit. If you collect ₹90K GST on sales and paid ₹60K GST on purchases, net GST payable is only ₹30K." },
      { question: "What is the income tax on business profit?", answer: "Sole proprietorship: taxed at individual slab rates (0-30%). Partnership: 30% flat. Company: 22% (new regime under Sec 115BAA, no MAT) or 25% (turnover ≤₹400Cr, regular). LLP: 30%. Choose business structure based on tax efficiency." },
      { question: "What expenses can I deduct from business profit?", answer: "Deductible: rent, salaries, utilities, depreciation, loan interest, marketing, professional fees, travel (business purpose), repairs and maintenance, insurance. Not deductible: personal expenses, penalties, TDS on non-compliant payments (40(a)(ia))." },
      { question: "What is presumptive taxation for small businesses?", answer: "Section 44AD: businesses with turnover ≤₹3Cr can declare 6% (digital receipts) or 8% (cash) of turnover as profit without maintaining detailed accounts. Section 44ADA: professionals with receipts ≤₹75L can declare 50% as profit." },
    ],
    blogSlugs: ["business-profit-calculation", "gst-on-business-income", "net-profit-vs-gross-profit", "presumptive-taxation-44ad", "business-expense-deductions"],
  },
  {
    slug: "step-up-sip-calculator",
    name: "Step-Up SIP Calculator",
    shortName: "Step-Up SIP",
    description: "Calculate SIP returns with annual increment in monthly investment",
    icon: "stepup",
    category: "investment",
    formula: "FV with step-up = Σ [P×(1+g)^t × ((1+r)^(n-t+1) − 1) / r]",
    h1: "Step-Up SIP Calculator India 2025 — Growing SIP Calculator",
    intro: "Calculate wealth accumulation with a Step-Up SIP where you increase your monthly investment annually. See how increasing SIP by 10% per year dramatically boosts your corpus.",
    howItWorks: "Enter starting monthly SIP, annual step-up percentage, expected return, and tenure. The calculator shows final corpus with step-up vs flat SIP comparison.",
    fields: [
      { label: "Starting Monthly SIP (₹)", type: "number", placeholder: "e.g. 5000" },
      { label: "Annual Step-Up (%)", type: "number", placeholder: "e.g. 10" },
      { label: "Expected Annual Return (%)", type: "number", placeholder: "e.g. 12" },
      { label: "Investment Period (Years)", type: "number", placeholder: "e.g. 20" },
    ],
    examples: [
      { label: "₹5K/month, 10% step-up, 12% return, 20 years", inputs: { monthly: 5000, stepup: 10, rate: 12, years: 20 }, result: "Step-Up Corpus: ₹1.21Cr | Flat SIP Corpus: ₹49.96L | Extra Wealth: ₹71L" },
      { label: "₹3K/month, 15% step-up, 12% return, 25 years", inputs: { monthly: 3000, stepup: 15, rate: 12, years: 25 }, result: "Step-Up Corpus: ₹2.48Cr | Flat SIP: ₹57.1L | Extra: ₹1.91Cr" },
      { label: "₹10K/month, 10% step-up, 10% return, 15 years", inputs: { monthly: 10000, stepup: 10, rate: 10, years: 15 }, result: "Step-Up Corpus: ₹68.5L | Flat SIP: ₹41.4L | Extra: ₹27.1L" },
    ],
    faqs: [
      { question: "What is Step-Up SIP?", answer: "Step-Up SIP (also called top-up SIP) is a variant where you increase your monthly SIP amount by a fixed percentage each year. Most fund houses allow 10-25% annual step-up. Aligns investment growth with salary increments." },
      { question: "By how much should I step up my SIP?", answer: "Match your expected annual salary increment: if you get 10% hike, increase SIP by 10%. Even a 5% annual step-up significantly boosts corpus over 15-20 years. ₹5K flat for 20 years at 12% = ₹50L. With 10% step-up = ₹1.21Cr — 2.4× more." },
      { question: "Do all mutual funds offer step-up SIP?", answer: "Yes, most major fund houses (SBI MF, HDFC MF, ICICI MF, Axis MF) offer step-up SIP facility. You can set it up during SIP registration or modify later. Some apps (Groww, Zerodha Coin) allow step-up configuration easily." },
      { question: "Can I reduce step-up SIP amount?", answer: "Yes, you can modify or cancel the step-up instruction before it triggers. Most fund houses require 30 days notice before the anniversary date. You can also skip a step-up for a year and resume the next year." },
      { question: "Is step-up SIP better than lump sum top-up?", answer: "Both work. Step-up SIP is automatic and disciplined — the increment is pre-set. Lump-sum top-up requires active decision and available funds. For salaried investors, step-up SIP aligned with annual increment is simpler and more effective." },
    ],
    blogSlugs: ["step-up-sip-guide", "how-step-up-sip-works", "step-up-sip-vs-flat-sip", "best-step-up-sip-funds", "sip-increment-calculator"],
  },
  {
    slug: "elss-calculator",
    name: "ELSS Calculator",
    shortName: "ELSS",
    description: "Calculate ELSS mutual fund returns and tax savings under 80C",
    icon: "elss",
    category: "investment",
    formula: "Tax Saved = Investment × Tax Rate | Returns = P × (1+r)^3 (minimum lock-in)",
    h1: "ELSS Calculator India 2025 — Tax Saving Mutual Fund Calculator",
    intro: "Calculate your ELSS (Equity Linked Savings Scheme) returns and tax savings. ELSS offers the highest potential returns among all 80C investments with just a 3-year lock-in.",
    howItWorks: "Enter ELSS investment amount, expected return rate, and your tax slab. The calculator shows maturity value, tax saved, and effective cost of investment after tax benefit.",
    fields: [
      { label: "ELSS Investment Amount (₹)", type: "number", placeholder: "e.g. 150000" },
      { label: "Expected Annual Return (%)", type: "number", placeholder: "e.g. 12" },
      { label: "Your Tax Slab (%)", type: "select", options: ["5%", "10%", "15%", "20%", "30%"] },
      { label: "Investment Period (Years)", type: "number", placeholder: "3" },
    ],
    examples: [
      { label: "₹1.5L ELSS, 12% return, 30% slab, 10 years", inputs: { amount: 150000, rate: 12, slab: 30, years: 10 }, result: "Maturity: ₹4,65,877 | Tax Saved: ₹46,800 | Effective Cost: ₹1,03,200" },
      { label: "₹1.5L ELSS, 15% return, 20% slab, 5 years", inputs: { amount: 150000, rate: 15, slab: 20, years: 5 }, result: "Maturity: ₹3,01,703 | Tax Saved: ₹31,200 | Effective Cost: ₹1,18,800" },
      { label: "₹50K ELSS SIP/year, 12% return, 30% slab, 15 years", inputs: { amount: 50000, rate: 12, slab: 30, years: 15 }, result: "Corpus: ₹2.49L/year | Total Tax Saved: ₹7L+ | Total Corpus: ₹30L+" },
    ],
    faqs: [
      { question: "What is ELSS?", answer: "ELSS (Equity Linked Savings Scheme) is an equity mutual fund category that qualifies for 80C tax deduction. It has the shortest lock-in (3 years) among all 80C investments and highest potential returns (12-15% historical CAGR). Losses after 3 years are taxable as LTCG." },
      { question: "How much tax can I save with ELSS?", answer: "Maximum ELSS investment for 80C: ₹1,50,000. Tax saved at 30% slab: ₹46,800 (including 4% cess). At 20% slab: ₹31,200. At 5% slab: ₹7,800. Only available in old tax regime." },
      { question: "What is the ELSS lock-in period?", answer: "3 years from date of each investment (for SIP, each instalment has its own 3-year lock-in). You cannot withdraw before 3 years, not even during financial emergency. After 3 years, LTCG above ₹1.25L is taxed at 12.5%." },
      { question: "Which ELSS fund is best in 2025?", answer: "Top ELSS funds by 5-year CAGR (indicative): Mirae Asset ELSS ~15%, Quant ELSS ~18%, Canara Robeco ELSS ~14%, Axis ELSS ~13%, SBI ELSS ~13%. Past performance doesn't guarantee future returns. Choose based on consistent track record and fund house reputation." },
      { question: "ELSS vs PPF: which is better for 80C?", answer: "ELSS: Higher returns (12-15%), only 3-year lock-in, market risk, LTCG applicable. PPF: Guaranteed 7.1%, 15-year lock-in, zero risk, completely tax-free. Ideal strategy: ELSS for higher corpus + PPF for stability. Combine both for balanced 80C portfolio." },
    ],
    blogSlugs: ["elss-tax-saving-guide", "best-elss-funds-2025", "elss-vs-ppf", "elss-sip-strategy", "ltcg-on-elss-redemption"],
  },
  {
    slug: "gratuity-calculator-2025",
    name: "Gratuity Calculator 2025",
    shortName: "Gratuity",
    description: "Calculate gratuity amount under the Payment of Gratuity Act",
    icon: "gratuity",
    category: "payroll",
    formula: "Gratuity = (Last Salary × 15/26) × Years of Service",
    h1: "Gratuity Calculator India 2025 — Payment of Gratuity Act",
    intro: "Calculate your gratuity amount accurately under the Payment of Gratuity Act, 1972. Find out exactly how much you're entitled to after 5 years of service.",
    howItWorks: "Enter your last drawn basic salary (basic + DA), and years of service. The calculator applies the standard formula and shows taxable vs tax-exempt portions.",
    fields: [
      { label: "Last Basic + DA Salary (₹/month)", type: "number", placeholder: "e.g. 50000" },
      { label: "Years of Service", type: "number", placeholder: "e.g. 10" },
      { label: "Employee Type", type: "select", options: ["Covered under Gratuity Act", "Not covered (private formula)"] },
    ],
    examples: [
      { label: "Salary ₹50K, 10 years (Act covered)", inputs: { salary: 50000, years: 10 }, result: "Gratuity: ₹2,88,462 | Tax-Free: ₹2,88,462 | Taxable: ₹0 (within ₹20L limit)" },
      { label: "Salary ₹80K, 15 years (Act covered)", inputs: { salary: 80000, years: 15 }, result: "Gratuity: ₹6,92,308 | Tax-Free: ₹6,92,308 | Taxable: ₹0" },
      { label: "Salary ₹2L, 20 years (Act covered)", inputs: { salary: 200000, years: 20 }, result: "Gratuity: ₹23,07,692 | Tax-Free: ₹20,00,000 | Taxable: ₹3,07,692" },
    ],
    faqs: [
      { question: "What is the gratuity formula?", answer: "For Act-covered employees: Gratuity = (Basic + DA) / 26 × 15 × Years of service. For non-covered: (Basic + DA) / 30 × 15 × Years. The 26-day month (excluding Sundays) is used for Act-covered; 30-day month for others." },
      { question: "What is the minimum service for gratuity?", answer: "Minimum 5 years continuous service. Exception: death or disability — gratuity is paid even before 5 years. For factories/mines: 4 years + 240 working days = eligible. For other establishments: 4 years + 190 days (5-day week) = eligible." },
      { question: "What is the maximum tax-free gratuity?", answer: "Maximum tax-exempt gratuity for private sector employees: ₹20 lakh (raised from ₹10L in 2019). Government employees: fully exempt. If gratuity exceeds ₹20L, the excess is taxable as salary income in the year of receipt." },
      { question: "When must gratuity be paid?", answer: "Within 30 days of it becoming payable (resignation, retirement, death, disability). Delay beyond 30 days: simple interest at the rate specified by the government. Employee must apply in Form I; employer responds with Form L (acceptance) or Form M (rejection)." },
      { question: "Is gratuity payable if I resign after 5 years?", answer: "Yes. Resignation after completing 5 years (or 4 years + 240 days) makes you eligible for gratuity. The employer cannot withhold gratuity unless there's a proven case of willful omission, destruction of property, or riotous conduct." },
    ],
    blogSlugs: ["gratuity-calculation-guide", "gratuity-eligibility-rules", "gratuity-tax-exemption", "gratuity-act-1972-explained", "how-to-claim-gratuity"],
  },
  {
    slug: "epf-calculator",
    name: "EPF Calculator",
    shortName: "EPF",
    description: "Calculate EPF corpus at retirement with interest projections",
    icon: "epf",
    category: "payroll",
    formula: "Monthly contribution = 12% of Basic | Annual interest at current EPF rate",
    h1: "EPF Calculator India 2025 — Employee Provident Fund Calculator",
    intro: "Calculate your EPF (Employee Provident Fund) corpus at retirement. See year-by-year balance growth with current EPF interest rate of 8.25% p.a.",
    howItWorks: "Enter monthly basic salary, current EPF balance, current age, and retirement age. The calculator projects your EPF corpus including both employee and employer contributions.",
    fields: [
      { label: "Monthly Basic Salary (₹)", type: "number", placeholder: "e.g. 30000" },
      { label: "Current EPF Balance (₹)", type: "number", placeholder: "e.g. 500000" },
      { label: "Current Age (Years)", type: "number", placeholder: "e.g. 30" },
      { label: "Retirement Age (Years)", type: "number", placeholder: "58" },
    ],
    examples: [
      { label: "₹30K basic, ₹5L current balance, age 30-58", inputs: { basic: 30000, balance: 500000, age: 30, retirement: 58 }, result: "EPF Corpus at 58: ₹1.28Cr | Total Contribution: ₹48.4L | Interest: ₹79.6L" },
      { label: "₹50K basic, ₹2L balance, age 25-58", inputs: { basic: 50000, balance: 200000, age: 25, retirement: 58 }, result: "EPF Corpus at 58: ₹2.84Cr | Total Contribution: ₹99L | Interest: ₹1.85Cr" },
      { label: "₹20K basic, ₹0 balance, age 22-58", inputs: { basic: 20000, balance: 0, age: 22, retirement: 58 }, result: "EPF Corpus at 58: ₹1.34Cr | Total Contribution: ₹31.1L | Interest: ₹1.03Cr" },
    ],
    faqs: [
      { question: "What is the current EPF interest rate?", answer: "EPF interest rate for FY 2024-25 is 8.25% per annum (announced by EPFO). Interest is calculated monthly on the minimum balance and credited at year-end. It's tax-free up to ₹2.5L annual contribution (₹5L if no employer contribution)." },
      { question: "How is EPF contribution calculated?", answer: "Employee: 12% of Basic Salary. Employer: 12% of Basic — split as 8.33% to EPS (Employees' Pension Scheme, max ₹1,250/month) and 3.67% to EPF. Plus 0.5% EDLI insurance and 0.5% admin charges paid by employer." },
      { question: "When can I withdraw EPF?", answer: "Full withdrawal: retirement at 58, or 2 months after leaving employment. Partial withdrawal: housing (after 5 years), medical (any time), marriage (after 7 years), education (after 7 years), natural calamity. COVID-19 special withdrawal was a one-time facility." },
      { question: "Is EPF withdrawal taxable?", answer: "Tax-free if withdrawn after 5 years of continuous service. If withdrawn before 5 years: TDS @10% (if PAN furnished) on employer contribution + interest + employee contribution interest. Tax applies at slab rate if 10% TDS is not sufficient." },
      { question: "What is UAN and how to activate it?", answer: "UAN (Universal Account Number) is a 12-digit number allocated by EPFO to every EPF member. It stays the same across employers. Activate at unifiedportal-mem.epfindia.gov.in using your member ID, Aadhaar, PAN, and mobile number." },
    ],
    blogSlugs: ["epf-guide-2025", "epf-withdrawal-rules", "how-to-check-epf-balance", "epf-vs-nps", "epf-interest-rate-history"],
  },
  {
    slug: "sukanya-samriddhi-calculator",
    name: "Sukanya Samriddhi Calculator",
    shortName: "SSY",
    description: "Calculate Sukanya Samriddhi Yojana maturity amount for girl child",
    icon: "ssy",
    category: "investment",
    formula: "Annual compounding at current SSY rate (8.2%)",
    h1: "Sukanya Samriddhi Yojana Calculator 2025 — SSY Maturity Calculator",
    intro: "Calculate the maturity amount for Sukanya Samriddhi Yojana (SSY) for your daughter. The scheme offers 8.2% p.a. with complete tax exemption under EEE status.",
    howItWorks: "Enter annual deposit amount and your daughter's current age. The calculator shows the maturity amount at age 21 and withdrawal amount at age 18 for education.",
    fields: [
      { label: "Annual Deposit (₹)", type: "number", placeholder: "e.g. 150000" },
      { label: "Daughter's Current Age (Years)", type: "number", placeholder: "e.g. 5" },
      { label: "Current SSY Rate (%)", type: "number", placeholder: "8.2" },
    ],
    examples: [
      { label: "₹1.5L/year, daughter age 5, 8.2% rate", inputs: { annual: 150000, age: 5, rate: 8.2 }, result: "Maturity at age 21: ₹63.4L | Total Invested: ₹22.5L (15 years) | Tax-Free Gain: ₹40.9L" },
      { label: "₹1L/year, daughter age 1, 8.2% rate", inputs: { annual: 100000, age: 1, rate: 8.2 }, result: "Maturity at age 21: ₹46.2L | Invested: ₹15L | Gain: ₹31.2L" },
      { label: "₹50K/year, daughter age 8, 8.2% rate", inputs: { annual: 50000, age: 8, rate: 8.2 }, result: "Maturity at age 21: ₹17.7L | Invested: ₹7.5L | Gain: ₹10.2L" },
    ],
    faqs: [
      { question: "What is Sukanya Samriddhi Yojana?", answer: "SSY is a government savings scheme exclusively for the girl child. Parents/guardians open the account for a girl child below 10 years. It offers 8.2% p.a. interest (Q1 2025-26) with EEE tax status — making it one of the best schemes for girl child education and marriage." },
      { question: "What is the current SSY interest rate?", answer: "SSY interest rate for Q1 FY 2025-26 is 8.2% per annum, compounded annually. It's the highest among all government small savings schemes. Rate is reviewed quarterly by the government." },
      { question: "When can I withdraw SSY amount?", answer: "Full withdrawal: at age 21 of the girl (account maturity). Partial withdrawal: up to 50% of previous year-end balance when girl turns 18 (for higher education). Premature closure: only for specific reasons (girl's death, life-threatening illness, marriage after 18)." },
      { question: "How many SSY accounts can I open?", answer: "Maximum 2 SSY accounts per family (one per girl child). Exception: twins/triplets as second birth — can open 3 accounts. Account must be opened before girl child turns 10 years of age." },
      { question: "Where can I open Sukanya Samriddhi account?", answer: "Post offices, SBI, Bank of Baroda, Canara Bank, Punjab National Bank, HDFC Bank, ICICI Bank, Axis Bank, Kotak Bank, and other authorised banks. Minimum deposit: ₹250/year. Maximum: ₹1.5L/year. Deposits must be made for 15 years." },
    ],
    blogSlugs: ["sukanya-samriddhi-yojana-guide", "ssy-interest-rate-2025", "ssy-vs-ppf-for-girl-child", "ssy-withdrawal-rules", "sukanya-samriddhi-tax-benefits"],
  },
  {
    slug: "inflation-calculator",
    name: "Inflation Calculator",
    shortName: "Inflation",
    description: "Calculate purchasing power impact of inflation on your money",
    icon: "inflation",
    category: "finance",
    formula: "Future Value = Present Value × (1 + inflation rate)^years",
    h1: "Inflation Calculator India 2025 — Purchasing Power Calculator",
    intro: "Calculate how inflation erodes your money's purchasing power over time. Understand how much you need to save today to maintain your lifestyle in the future.",
    howItWorks: "Enter current amount, expected inflation rate, and time period. The calculator shows future equivalent value and how much more money you'll need to maintain the same purchasing power.",
    fields: [
      { label: "Current Amount (₹)", type: "number", placeholder: "e.g. 100000" },
      { label: "Expected Inflation Rate (%)", type: "number", placeholder: "e.g. 6" },
      { label: "Time Period (Years)", type: "number", placeholder: "e.g. 10" },
    ],
    examples: [
      { label: "₹1L today, 6% inflation, 10 years", inputs: { amount: 100000, inflation: 6, years: 10 }, result: "Future equivalent: ₹1,79,085 | Purchasing power lost: 44%" },
      { label: "Monthly expenses ₹50K, 6% inflation, 20 years", inputs: { amount: 50000, inflation: 6, years: 20 }, result: "Future monthly need: ₹1,60,357 | 3.2× current expenses" },
      { label: "₹1Cr retirement corpus, 5% inflation, 15 years", inputs: { amount: 10000000, inflation: 5, years: 15 }, result: "Real value in 15 years: ₹48.1L | Inflation destroys ₹51.9L of value" },
    ],
    faqs: [
      { question: "What is the current inflation rate in India?", answer: "India's CPI (Consumer Price Index) inflation target is 4% (RBI's medium-term target). Actual inflation varies: food inflation often 6-8%, core inflation (excluding food & fuel) around 4-5%. Use 5-6% for long-term financial planning." },
      { question: "How does inflation affect savings?", answer: "If savings earn less than inflation, real value falls. Example: FD at 7% with 6% inflation = only 1% real return. Equity investments historically outpace inflation by 6-8% annually over long periods, making them essential for wealth preservation." },
      { question: "What is real vs nominal return?", answer: "Nominal return: stated return (e.g., FD 7%). Real return: return after inflation. Real return = Nominal − Inflation (approximately). FD 7% − 6% inflation = 1% real return. Equity 12% − 6% inflation = 6% real return." },
      { question: "How much should I save for retirement considering inflation?", answer: "Apply the inflation factor to your current expenses. If monthly expenses are ₹50K now and you retire in 25 years with 6% inflation, you'll need ₹2.15L/month. Build a corpus that generates this inflation-adjusted income. Rule of thumb: 25-30× annual retirement expenses." },
      { question: "Which investments beat inflation in India?", answer: "Consistent inflation beaters: Equity mutual funds (12-15% vs 6% inflation), Real estate (8-12%), Gold (8-10%), REITs (8-10%). Inflation losers: Savings account (3-4%), FD only partially beats inflation. Always invest a portion in equity to preserve wealth." },
    ],
    blogSlugs: ["inflation-impact-on-savings", "real-vs-nominal-returns", "how-to-beat-inflation-india", "inflation-proof-investments", "retirement-planning-with-inflation"],
  },
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    shortName: "Retirement",
    description: "Calculate how much you need to save for a comfortable retirement",
    icon: "retirement",
    category: "investment",
    formula: "Corpus needed = Annual expenses × 25 (4% withdrawal rule)",
    h1: "Retirement Calculator India 2025 — Retirement Planning Calculator",
    intro: "Calculate exactly how much retirement corpus you need and how much to save monthly to achieve your retirement goal. Plan a financially secure retirement with confidence.",
    howItWorks: "Enter current age, retirement age, monthly expenses, and expected returns. The calculator factors in inflation to show the corpus needed and required monthly savings.",
    fields: [
      { label: "Current Age (Years)", type: "number", placeholder: "e.g. 30" },
      { label: "Retirement Age (Years)", type: "number", placeholder: "60" },
      { label: "Current Monthly Expenses (₹)", type: "number", placeholder: "e.g. 50000" },
      { label: "Expected Return on Investment (%)", type: "number", placeholder: "e.g. 12" },
    ],
    examples: [
      { label: "Age 30, retire at 60, ₹50K/month expenses", inputs: { age: 30, retirement: 60, expenses: 50000, rate: 12 }, result: "Corpus needed: ₹5.7Cr | Monthly SIP required: ₹16,500 | At 12% return" },
      { label: "Age 25, retire at 55, ₹40K/month expenses", inputs: { age: 25, retirement: 55, expenses: 40000, rate: 12 }, result: "Corpus needed: ₹5.4Cr | Monthly SIP required: ₹8,800 | Start early advantage!" },
      { label: "Age 40, retire at 60, ₹80K/month expenses", inputs: { age: 40, retirement: 60, expenses: 80000, rate: 12 }, result: "Corpus needed: ₹7.3Cr | Monthly SIP: ₹1,12,000 | Late start = higher SIP" },
    ],
    faqs: [
      { question: "How much money do I need to retire in India?", answer: "Use the 4% withdrawal rule: Annual retirement expenses × 25. If monthly expenses at retirement (inflation-adjusted) are ₹1L, annual = ₹12L, corpus needed = ₹3Cr. Corpus at 4% withdrawal sustains for 30+ years. Indian rule of thumb: 25-30× annual expenses." },
      { question: "How much should I save for retirement at 30?", answer: "To retire at 60 with ₹50K/month (today's value): save ~₹16,500/month in equity SIP earning 12% CAGR. Starting at 35 requires ₹27,000/month. At 40: ₹48,000/month. Every 5-year delay nearly doubles the required saving. Start at 25-30 for the best outcome." },
      { question: "What is the 4% rule for retirement?", answer: "The 4% rule: withdraw 4% of corpus annually in retirement. This historically sustains the corpus for 30+ years. Corpus needed = Annual withdrawal / 0.04 = Annual expenses × 25. Adjust for India's higher inflation (use 3.5% withdrawal = 28× annual expenses for safety)." },
      { question: "Which investments are best for retirement in India?", answer: "Accumulation phase (working years): Equity mutual funds SIP (70%), PPF (20%), NPS (10%). Transition phase (5 years before retirement): Shift to balanced/hybrid funds. Post-retirement: Senior citizen FD (7.5-9%), SCSS (8.2%), PMVVY, SWP from balanced mutual funds." },
      { question: "Is EPF enough for retirement?", answer: "EPF alone is unlikely sufficient. EPF provides ~₹1-3Cr for most salaried employees — enough for basic needs but not comfortable lifestyle. Supplement with SIP in equity mutual funds, NPS, and PPF for comprehensive retirement planning. Aim for at least 4-5 income streams in retirement." },
    ],
    blogSlugs: ["retirement-planning-india", "how-much-to-retire-india", "retirement-corpus-calculation", "best-retirement-investments", "early-retirement-fire-india"],
  },
];

export function getNewCalculatorBySlug(slug: string): NewCalculator | undefined {
  return NEW_CALCULATORS.find((c) => c.slug === slug);
}

export function getAllNewCalculatorSlugs(): string[] {
  return NEW_CALCULATORS.map((c) => c.slug);
}
